spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: h2
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false